version: '3.9'
services:
  gcs-emulator:
    container_name: gcs-emulator
    image: oittaa/gcp-storage-emulator
    environment:
      - PORT=9023
    ports:
      - 9023:9023
    volumes:
      - ./gcsserver/data:/storage
    command: start --default-bucket=test-bucket --in-memory

  app:
    build: .
    container_name: app
    image: app
    ports:
      - 8080:8080
    depends_on:
      - gcs-emulator

volumes:
  pg-data: