app:
  name: 'go-clean-fileupload'
  version: '1.0.0'

http:
  port: '8080'
  read_timeout: 10000000000
  write_timeout: 5000000000
  shutdown_timeout: 10000000000

logger:
  log_level: 'debug'

postgres:
  pool_max: 2
